version: '3.8'
services:
  tor:
    image: localhost/tor:1.1
    container_name: tor
    restart: always
    stop_grace_period: 5s
    ports:
      - "0.0.0.0:9050:9050/tcp"
    volumes:
      - "~/.cache/log/tor:/var/log/tor"
      - "~/.cache/data/tor:/var/lib/tor"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256m
