#!/bin/sh
set -eu
TORRC=/etc/tor/torrc
{
  echo "# Generated by tor-entrypoint.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# Mode: relay=${TOR_RELAY:-0}"
  echo "SocksPort 0.0.0.0:${TOR_SOCKET_PORT:-9050}"
  echo "Log notice stdout"
  echo "Log notice file /var/log/tor/notices.log"
  if [ "${TOR_RELAY:-0}" != "0" ]; then
    echo ""
    echo "# Relay mode — bind to localhost for NAT environments (slirp4netns)"
    echo "Address 127.0.0.1"
    echo "ORPort ${TOR_OR_PORT:-9001}"
    echo "DirPort ${TOR_DIR_PORT:-9030}"
    [ -n "${TOR_NICKNAME:-}" ] && echo "Nickname ${TOR_NICKNAME}"
    [ -n "${TOR_CONTACT_INFO:-}" ] && echo "ContactInfo ${TOR_CONTACT_INFO}"
    echo "BandwidthRate ${TOR_BANDWIDTH_RATE:-5242880}"
    echo "BandwidthBurst ${TOR_BANDWIDTH_BURST:-10485760}"
  fi
} > "$TORRC"
exec tor
